name: Check files workflow

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install
        run: npm install
      - name: Check files
        run: npm run check-files
